project:
  type: book
  execute-dir: file


book:
  title: "technical-tidbits"
  author: "MDG"
  date: "4/1/2026"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



